
services:
  db:
    image: postgres:15
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  backend:
    build:
      context: ./aiforghana-helpdesk
    command: gunicorn -k uvicorn.workers.UvicornWorker aiforghana_helpdesk_api.main:app --bind 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - ./aiforghana-helpdesk:/app
      - ./model_cache:/app/model_cache
    expose:
      - "8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./aiforghana-next
      dockerfile: Dockerfile.prod
    volumes:
      - ./aiforghana-next/out:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres-data:
